# Generated by Django 5.1.3 on 2025-06-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_passport_number_student_pnfl'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[(1, 'Male'), (2, 'Female')], default='---', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='passport_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
