# Generated by Django 5.1.3 on 2025-06-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_student_gender_student_passport_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_attended_exam',
            field=models.BooleanField(default=False),
        ),
    ]
