# Generated by Django 5.1.3 on 2025-06-03 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_student_is_attended_exam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='pnfl',
            new_name='pinfl',
        ),
    ]
