# Generated by Django 5.1.3 on 2025-06-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_pnfl_student_pinfl'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_passed_exam',
            field=models.BooleanField(default=False),
        ),
    ]
