# Generated by Django 5.1.3 on 2025-06-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user_lang_user_registered_by_bot_user_tg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='additional_phone_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
