# Generated by Django 5.1.3 on 2025-06-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_student_additional_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_exam_exempt',
            field=models.BooleanField(default=False),
        ),
    ]
