# Generated by Django 5.1.3 on 2025-06-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_student_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='source',
            field=models.CharField(blank=True, default='web', max_length=50, null=True),
        ),
    ]
