version: '3.10'

services:
  db:
    container_name: olympiad
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root_password}
      POSTGRES_DB: ${POSTGRES_DB:-khiso_db}
    ports:
      - "5432:5432"
    volumes:
      - tift_backend_data:/var/lib/postgresql/data

  backend:
    container_name: backend
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=db
    env_file:
      - .env
    volumes:
      - .:/app
  bot:
    container_name: tift_bot
    build:
      context: .
    command: python manage.py bot
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=db
    env_file:
      - .env

volumes:
  tift_backend_data: {}

