name: Build and Push Docker Images

env:
  BACKEND_REPOSITORY: nodirbyte/tift-backend
  PROJECT_DIR: /home/devuser/pro/backend

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login (DockerHub)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Backend image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.BACKEND_REPOSITORY }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    runs-on: self-hosted
    needs: build
    defaults:
      run:
        working-directory: ${{ env.PROJECT_DIR }}

    steps:
      - name: Docker Login (DockerHub)
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Pull the latest images
        run: |
          echo "Pulling the latest backend image"
          docker pull ${{ env.BACKEND_REPOSITORY }}:latest

      - name: Migrate
        run: |
          echo "Applying migrations"
          docker compose -f docker-compose.yml run -i --rm backend python3 manage.py migrate

      - name: Restart
        run: |
          echo "Restarting services"
          docker compose -f docker-compose.yml up backend -d

      - name: Show processes
        run: |
          docker compose ps --all --format "table {{.ID}}\t{{.Service}}\t{{.State}}\t{{.Status}}\t{{.CreatedAt}}"