# Generated by Django 5.1.3 on 2025-05-28 06:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, verbose_name='Faculty Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Faculty Description')),
            ],
            options={
                'verbose_name': 'Faculty',
                'verbose_name_plural': 'Faculties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, verbose_name='Program Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Program Description')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, verbose_name='Study Type Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Study Type Description')),
            ],
            options={
                'verbose_name': 'Study Type',
                'verbose_name_plural': 'Study Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_online', models.BooleanField(default=False, verbose_name='Is Online Exam')),
                ('exam_date', models.DateTimeField()),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_faculties', to='university.faculty')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_programs', to='university.program')),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
            },
        ),
        migrations.AddField(
            model_name='faculty',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_programs', to='university.program', verbose_name='Program'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=100, verbose_name='Application Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Application Description')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
                ('exams', models.ManyToManyField(related_name='application_exams', to='university.exam', verbose_name='Exams')),
                ('faculties', models.ManyToManyField(related_name='application_set', to='university.faculty', verbose_name='Faculties')),
                ('programs', models.ManyToManyField(related_name='application_set', to='university.program', verbose_name='Programs')),
                ('study_types', models.ManyToManyField(related_name='application_studytypes', to='university.studytype', verbose_name='Study Types')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='StudentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('exam_result', models.CharField(blank=True, max_length=20, null=True)),
                ('is_transfer', models.BooleanField(default=False)),
                ('transfer_level', models.IntegerField(blank=True, null=True)),
                ('transcript', models.FileField(blank=True, null=True, upload_to='transcripts/')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_list', to='university.application')),
                ('exam_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_exam_applications', to='university.exam')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_applications', to='university.faculty')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_applications', to='university.program')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_applications', to='user.user')),
                ('study_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_applications', to='university.studytype')),
            ],
            options={
                'verbose_name': 'Student Application',
                'verbose_name_plural': 'Student Applications',
            },
        ),
    ]
