# Generated by Django 5.1.3 on 2025-05-28 12:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='score',
            field=models.FloatField(blank=True, null=True, verbose_name='Score'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, verbose_name='Subject Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Subject Description')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='university.faculty', verbose_name='Faculty')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('question_text', models.TextField(verbose_name='Question Text')),
                ('version_a', models.TextField(blank=True, null=True, verbose_name='Version A')),
                ('version_b', models.TextField(blank=True, null=True, verbose_name='Version B')),
                ('version_c', models.TextField(blank=True, null=True, verbose_name='Version C')),
                ('version_d', models.TextField(blank=True, null=True, verbose_name='Version D')),
                ('is_correct_a', models.BooleanField(default=False, verbose_name='Is Correct A')),
                ('is_correct_b', models.BooleanField(default=False, verbose_name='Is Correct B')),
                ('is_correct_c', models.BooleanField(default=False, verbose_name='Is Correct C')),
                ('is_correct_d', models.BooleanField(default=False, verbose_name='Is Correct D')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='university.subject', verbose_name='Subject')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['subject', 'question_text'],
            },
        ),
    ]
