# Generated by Django 5.1.3 on 2025-05-29 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_studentapplication_score_subject_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='is_online_exam',
            field=models.BooleanField(default=False, verbose_name='Is Online Exam'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='exam_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_exam_applications', to='university.exam'),
        ),
    ]
