# Generated by Django 5.1.3 on 2025-05-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_studentapplication_is_online_exam_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='faculty',
        ),
        migrations.AddField(
            model_name='faculty',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='faculty_subjects', to='university.subject', verbose_name='Subjects'),
        ),
    ]
