# Generated by Django 5.1.3 on 2025-05-31 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_alter_application_exams'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Application Description'),
        ),
        migrations.AddField(
            model_name='application',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Application Description'),
        ),
        migrations.AddField(
            model_name='application',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Application Title'),
        ),
        migrations.AddField(
            model_name='application',
            name='title_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Application Title'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Faculty Description'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Faculty Description'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Faculty Name'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Faculty Name'),
        ),
        migrations.AddField(
            model_name='program',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Program Description'),
        ),
        migrations.AddField(
            model_name='program',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Program Description'),
        ),
        migrations.AddField(
            model_name='program',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Program Name'),
        ),
        migrations.AddField(
            model_name='program',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Program Name'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text_ru',
            field=models.TextField(null=True, verbose_name='Question Text'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text_uz',
            field=models.TextField(null=True, verbose_name='Question Text'),
        ),
        migrations.AddField(
            model_name='question',
            name='version_a_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Version A'),
        ),
        migrations.AddField(
            model_name='question',
            name='version_a_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Version A'),
        ),
        migrations.AddField(
            model_name='question',
            name='version_b_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Version B'),
        ),
        migrations.AddField(
            model_name='question',
            name='version_b_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Version B'),
        ),
        migrations.AddField(
            model_name='question',
            name='version_c_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Version C'),
        ),
        migrations.AddField(
            model_name='question',
            name='version_c_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Version C'),
        ),
        migrations.AddField(
            model_name='question',
            name='version_d_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Version D'),
        ),
        migrations.AddField(
            model_name='question',
            name='version_d_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Version D'),
        ),
        migrations.AddField(
            model_name='studytype',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Study Type Description'),
        ),
        migrations.AddField(
            model_name='studytype',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Study Type Description'),
        ),
        migrations.AddField(
            model_name='studytype',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Study Type Name'),
        ),
        migrations.AddField(
            model_name='studytype',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Study Type Name'),
        ),
        migrations.AddField(
            model_name='subject',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Subject Description'),
        ),
        migrations.AddField(
            model_name='subject',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Subject Description'),
        ),
        migrations.AddField(
            model_name='subject',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Subject Name'),
        ),
        migrations.AddField(
            model_name='subject',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Subject Name'),
        ),
    ]
