# Generated by Django 5.1.3 on 2025-05-31 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0006_application_description_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_text_ru',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_text_uz',
        ),
        migrations.RemoveField(
            model_name='question',
            name='version_a_ru',
        ),
        migrations.RemoveField(
            model_name='question',
            name='version_a_uz',
        ),
        migrations.RemoveField(
            model_name='question',
            name='version_b_ru',
        ),
        migrations.RemoveField(
            model_name='question',
            name='version_b_uz',
        ),
        migrations.RemoveField(
            model_name='question',
            name='version_c_ru',
        ),
        migrations.RemoveField(
            model_name='question',
            name='version_c_uz',
        ),
        migrations.RemoveField(
            model_name='question',
            name='version_d_ru',
        ),
        migrations.RemoveField(
            model_name='question',
            name='version_d_uz',
        ),
        migrations.AddField(
            model_name='question',
            name='lang',
            field=models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian')], default='uz', max_length=10, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='lang',
            field=models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian')], default='uz', max_length=20, verbose_name='Language'),
        ),
    ]
