# Generated by Django 5.1.3 on 2025-06-01 06:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0007_remove_question_question_text_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, verbose_name='Exam Type Name')),
                ('name_uz', models.CharField(max_length=100, null=True, verbose_name='Exam Type Name')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Exam Type Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Exam Type Description')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Exam Type Description')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Exam Type Description')),
            ],
            options={
                'verbose_name': 'Exam Type',
                'verbose_name_plural': 'Exam Types',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='exam_types',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_exam_types', to='university.examtype', verbose_name='Exam Type'),
        ),
    ]
