# Generated by Django 5.1.3 on 2025-06-01 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0008_examtype_application_exam_types'),
        ('user', '0003_student_gender_student_passport_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapplication',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='user.student', verbose_name='Student'),
        ),
    ]
