# Generated by Django 5.1.3 on 2025-06-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0009_alter_studentapplication_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Faculty Code'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Price'),
        ),
    ]
