# Generated by Django 5.1.3 on 2025-06-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0010_faculty_code_faculty_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='price',
        ),
        migrations.AddField(
            model_name='faculty',
            name='day_price',
            field=models.FloatField(default=0.0, verbose_name='Day Price'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='night_price',
            field=models.FloatField(default=0.0, verbose_name='Night Price'),
        ),
    ]
