# Generated by Django 5.1.3 on 2025-06-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0012_alter_studentapplication_faculty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='study_duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Study Duration (years)'),
        ),
    ]
