# Generated by Django 5.1.3 on 2025-06-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0013_program_study_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='day_price',
            field=models.TextField(blank=True, null=True, verbose_name='Day Price'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='night_price',
            field=models.TextField(blank=True, null=True, verbose_name='Night Price'),
        ),
    ]
