# Generated by Django 5.1.3 on 2025-06-18 14:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0014_alter_faculty_day_price_alter_faculty_night_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('study_duration', models.IntegerField(blank=True, null=True, verbose_name='Study Duration (years)')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duration_faculties', to='university.faculty', verbose_name='Faculty')),
                ('study_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duration_study_types', to='university.studytype', verbose_name='Study Type')),
            ],
            options={
                'verbose_name': 'Study Duration',
                'verbose_name_plural': 'Study Durations',
                'ordering': ['faculty'],
            },
        ),
    ]
