# Generated by Django 5.1.3 on 2025-06-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0015_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='study_types',
            field=models.ManyToManyField(related_name='program_study_types', to='university.studytype', verbose_name='Study Types'),
        ),
    ]
