# Generated by Django 5.1.3 on 2025-06-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0017_alter_duration_study_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='external_price',
            field=models.TextField(blank=True, null=True, verbose_name='External Price'),
        ),

    ]
