# Generated by Django 5.1.3 on 2025-06-22 09:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0018_faculty_external_price_faculty_study_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyTypeFaculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_study_types', to='university.faculty', verbose_name='Faculty Name')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_study_types', to='university.program', verbose_name='Program Name')),
                ('study_type', models.ManyToManyField(related_name='study_type_faculties', to='university.studytype', verbose_name='Study Type Name')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
