# Generated by Django 5.1.3 on 2025-07-05 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0020_alter_studytypefaculty_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to='university.program', verbose_name='Program'),
        ),
    ]
