# Generated by Django 5.1.3 on 2025-07-13 10:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0021_alter_faculty_program'),
        ('user', '0014_dummymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDtmResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('dtm_file', models.FileField(blank=True, null=True, upload_to='dtm_file')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dtm_results', to='user.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
