ortga = "🔙 Ortga"
menuga_uz = '🔙 Asosiy menu qaytish'
menuga_ru = '🔙 Главное меню'
nazad = "🔙 Назад"

uz_text = "🇺🇿 O'zbek"
ru_text = "🇷🇺 Русский"

uz = {
    "menu_text": "Xush kelibsiz {name}! 🌟\nIltimos, telefon raqamingizni yuboring.\nBu raqam bilan siz TIFT saytiga ham kirish imkonini qolga kiritasiz.\nShuning uchun telefon raqamingizni to‘g‘ri va aniq kiriting.",
    "sign_in_text": "🗝 Hisobingizga kirish uchun parolni tering",
    "enter_sms": "📲 Telefon raqamingizga kelgan SMSni kiriting\n⏱️ Agar kod kelmasa shunchaki ixtiyoriy son kiriting va boshqa sms kodni kuting",
    "enter_sms_error": "❌ Telefon raqamga SMS jo‘natishda muammo yuzaga keldi\n🔄 Qaytadan urinib koring",
    "enter_fullname": "✅ Kod qabul qilindi. To'liq F.I.O kiriting \nMasalan: (Azizov Aziz Aziz o'g'li)",
    "sms_wrong": "❌ Kod qabul qilinmadi 🔄 Qayta urinib ko‘ring",
    "use_btn": "🔘 Iltimos tugmalardan foydalaning",
    "password_text": "🔐 Kelajakda TIFT accountingizga kirish uchun maxfiy parol yarating",
    "confirm_password_text": "🔐 Yaratgan parolingizni yana bir marotaba kiriting va tasdiqlang",
    "confirm_error_text": "🔐 Parollar mos kelmadi. Iltimos, qaytadan kiriting",
    "confirm_info": "✅ Tabriklaymiz! Siz muvaffaqiyatli ro‘yxatdan o‘tdingiz!",
    "main_menu": "🏠 Bosh sahifa",
    "login_error": "❌ Kod mos kelmadi qaytadan urinib koring",
    "contact_admin": "📩 Xabaringizni yozing yoki call centerga murojat qiling +998-71-202-92-29",
    "contact_success": "✅ Xabaringiz adminlarga yuborildi. Tez orada javob kuting... 🕒\nYana biron murojatingiz bolsa yozing ✍️",
    "phone_number_ask": "📞 Raqamni yuborish",
    "ask_number_login": "📲 Hisobingizga kirish uchun telefon raqamingizni yuboring.",
    "ask_password": "🔐 Hisob parolini kiriting",
    "no_user": "❌ Bunday foydalanuvchi mavjud emas",
    "choose_subject": "📖 Olimpiadada qatnashadigan faningizni belgilang",
    "contact_reply": "☎️ Biz bilan aloqa",
    "choose_study_type": "🏫 Ta'lim shaklini tanlang",
    "choose_faculty": "🏛 Fakultetlardan birini tanlang",
    "enter_passport_info": "🪪 Passport seriya va raqamini kiriting:\nMasalan: AD1234567",
    "ask_right_pass": "⛓️‍💥 Passport malumotlarini xato kiritdingiz.\nQaytadan kiriting.",
    "birth_info_get": "📅 Tug'ilgan yilingiz oy va kunini tanlang yoki qolda kiriting (YYYY-MM-DD)",
    "choose_diploma": "📎 <i>Bitirganlik diplomingizni va pastida joylashgan raqamni yuboring</i>.",
    "ask_transcript": "📎 Transkript yoki akademik tavsiyanomani yuklang",
    "succes_exam": "🎓 Tabriklaymiz! Siz TIFT universiteti talabasiga aylandingiz",
    "no_succes_exam": "📉 Universitetga kirish bo'yicha minimal ballni to'play olmadingiz. Imtihonni qayta topshirish uchun aloqa-markaziga qo'ng'iroq qiling: 71 202 92 29",
    "no_questions": "❗️Savollar topilmadi.",
    "overview": "📝 <b>2025–2026 o‘quv yili uchun hujjatlarni topshirish</b>\n\nToshkent xalqaro moliyaviy boshqaruv va texnologiyalar universiteti 28 ta bakalavriat hamda 11 ta magistratura mutaxassisliklari bo'yicha hujjatlarni qabul qilmoqda. Hujjat topshirish uchun quyidagi tugmani bosing.",
    "choose_program": "📘 Ta'lim turini tanlang",
    "choose_course_text": "🎓 Nechanchi yil talabasi ekanligingizni tanlang",
    "verify_pending": "⏳ Sizning ma'lumotlaringizni tasdiqlaganimizcha biroz kuting",
    "not_verified": "⚠️ MY GOV saytida muammo yuzaga keldi. Birozdan so‘ng qaytadan urinib ko‘ring",
    "file_upload_succes": "✅ Diplom fayli muvaffaqiyatli saqlandi.",
    "file_upload_no": "❌ Faylni yuklashda xatolik yuz berdi.",
    "additional_phone_number_succes": "📞 Raqam ham muvaffaqiyatli saqlandi",
    "language_choose": "🧪 Imtihonda qatnashmoqchi bolgan tilingizni tanlang",
    "info_upload_succes": "✅ Arizangiz muvaffaqiyatli yaratildi.",
    "passport_already_exists": "⚠️ Bu passport ma'lumotlari orqali allaqachon ro'yxatdan o'tilgan",
    "ask_qualification": "🎓 Bitirgan o'qish joyingizni tanlang",
    "name_qualification_ask": "🏫 Bitirgan o‘quv dargohingiz nomini yozing",
    "ask_diploma": "📎 Bitirganlik diplomingizni yuboring",
    "additional_ask": "📞 Qo‘shimcha telefon raqamingizni kiriting",
    "wrong_birth": "To'g'ri formatda kiriting (YYYY-MM-DD)",
    "reset_password_sms_error": "📲 Sms kod xato yangi kelgan kodni kiriting",
    "reset_password_sent_sms_error": "😢 Sms kod jonatishda hato yuzaga keldi sizga boshqa kod jonatishga harakat qilamiz",
    "reset_password_success": "🥳 Yangi parol muvaffaqiyatli yangilandi"

}

ru = {
    "menu_text": "🌟 Добро пожаловать, {name}!\nПожалуйста, отправьте свой номер телефона.\nС его помощью вы также сможете войти на сайт TIFT.\nВведите номер телефона правильно и точно.",
    "sign_in_text": "🗝 Введите пароль для входа в аккаунт",
    "enter_sms": "📲 Введите SMS-код, отправленный на ваш номер телефона\n⏱️ Если код не пришёл, введите любое число и дождитесь нового кода",
    "enter_sms_error": "❌ Ошибка при отправке SMS на номер телефона\n🔄 Попробуйте снова",
    "enter_fullname": "✅ Код принят. Введите полное Ф.И.О\nПример: (Азизов Азиз Азиз угли)",
    "sms_wrong": "❌ Код неверный 🔄 Попробуйте снова",
    "use_btn": "🔘 Пожалуйста, используйте кнопки",
    "password_text": "🔐 Создайте секретный пароль для входа в аккаунт TIFT в будущем",
    "confirm_password_text": "🔐 Введите созданный пароль ещё раз для подтверждения",
    "confirm_error_text": "🔐 Пароли не совпадают. Пожалуйста, введите заново",
    "confirm_info": "✅ Поздравляем! Вы успешно зарегистрировались!",
    "main_menu": "🏠 Главная страница",
    "login_error": "❌ Код неверный. Попробуйте снова",
    "contact_admin": "📩 Напишите ваше сообщение или обратитесь в колл-центр по номеру +998-71-202-92-29",
    "contact_success": "✅ Ваше сообщение отправлено администраторам. Ожидайте ответа... 🕒\nЕсли у вас есть ещё обращения, напишите ✍️",
    "phone_number_ask": "📞 Отправить номер",
    "ask_number_login": "📲 Отправьте номер телефона для входа в аккаунт.",
    "ask_password": "🔐 Введите пароль от аккаунта",
    "no_user": "❌ Пользователь не найден",
    "choose_subject": "📖 Выберите предмет для участия в олимпиаде",
    "contact_reply": "☎️ Связаться с нами",
    "choose_study_type": "🏫 Выберите форму обучения",
    "choose_faculty": "🏛 Выберите факультет",
    "enter_passport_info": "🪪 Введите серию и номер паспорта:\nНапример: AD1234567",
    "ask_right_pass": "⛓️‍💥 Неправильно введены паспортные данные.\nВведите ещё раз.",
    "birth_info_get": "📅 Укажите дату рождения  или введите вручную (ГГГГ-ММ-ДД)",
    "choose_diploma": "📎 <i>Прикрепите диплом об окончании и номер, указанный под ним</i>.",
    "ask_transcript": "📎 Загрузите транскрипт или академическую справку",
    "succes_exam": "🎓 Поздравляем! Вы стали студентом университета TIFT",
    "no_succes_exam": "📉 Вы не набрали минимальный балл для поступления. Позвоните в контакт-центр для повторной сдачи экзамена: 71 202 92 29",
    "no_questions": "❗️Вопросы не найдены.",
    "overview": "<b>📝 Прием документов на 2025–2026 учебный год</b>\n\nТашкентский международный университет финансового управления и технологий принимает документы на 28 бакалавриатов и 11 магистратур. Нажмите кнопку ниже для подачи заявки.",
    "choose_program": "📘 Выберите направление обучения",
    "choose_course_text": "🎓 Выберите, на каком курсе вы учитесь",
    "verify_pending": "⏳ Подождите немного, пока мы проверяем ваши данные",
    "not_verified": "⚠️ Возникла проблема при получении данных с сайта MY GOV. Пожалуйста, попробуйте снова позже",
    "file_upload_succes": "✅ Файл диплома успешно сохранён.",
    "file_upload_no": "❌ Ошибка при загрузке файла.",
    "additional_phone_number_succes": "📞 Дополнительный номер успешно сохранён",
    "language_choose": "🧪 Выберите форму экзамена",
    "info_upload_succes": "✅ Ваша заявка успешно создана.",
    "passport_already_exists": "⚠️ По этим паспортным данным уже зарегистрирован пользователь",
    "ask_qualification": "🎓 Выберите учебное заведение, которое вы окончили",
    "name_qualification_ask": "🏫 Укажите название учебного заведения, которое вы окончили",
    "ask_diploma": "📎 Отправьте диплом об окончании",
    "additional_ask": "📞 Введите дополнительный номер телефона",
    "wrong_birth": "Введите в правильном формате (ГГГГ-ММ-ДД)",
    "reset_password_sms_error": "📲 Код из СМС неверный, введите новый полученный код",
    "reset_password_sent_sms_error": "😢 Произошла ошибка при отправке кода, мы попытаемся отправить новый код",
    "reset_password_success": "🥳 Новый пароль успешно обновлён"

}

all = {
    "lang_choice": "🌐 Tilni tanlang 🇺🇿\n🇷🇺 Выберите язык",
    "undefined_lang": "❗ Noma'lum til! Iltimos, tilni qayta tanlang.",
    "admin_answer": "📝 Javob matnini yozing"
}
